alter table alert_history add column status text default 'pending';
alter table alert_history add column resolved_at integer;
alter table alert_history add column threshold real;
alter table alert_history add column trace_id text;
alter table alert_history add column url text;
alter table alert_history add column release_name text;
alter table alert_history add column user_id text;
alter table alert_history add column device_id text;
alter table alert_history add column session_id text;
alter table alert_history add column path text;
